version: '2.2'
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      #- "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper01
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest    
    container_name: kafka01
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  node-be:
    container_name: node01
    image: webapp/node-be
    environment:
      BACKEND_PORT: 5000
    ports: 
      - 5000:5000
    build:
      context: ./node-be
      target: production
    command: npm run start

  vue-fe:
    container_name: vue01
    image: webapp/vue-fe
    ports: 
      - 8081:80
    build:
      context: ./vue-fe


  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: kloadgen
      MONGO_INITDB_ROOT_PASSWORD: kloadgen
    volumes:
      - mongo:/var/lib/mongo
      - mongodb:/data/db
  
  mongoexpress:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: kloadgen
      ME_CONFIG_MONGODB_ADMINPASSWORD: kloadgen
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'kloadgen'
      ME_CONFIG_SITE_BASEURL: /mongo-express/
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=PathPrefix(`/mongo-express`)"
        - "traefik.http.routers.backend.entrypoints=web"  
        - "traefik.http.middlewares.backend.stripprefix.prefixes=/mongo-express" 
    ports:
      - "8090:8081"

volumes:
  data01:
    driver: local
  mongo:
    driver: local
  mongodb:
    driver: local


networks:
  elastic:
    driver: bridge
